CREATE DATABASE SSMS;
USE SSMS;

CREATE TABLE STUDENT (
S_ID VARCHAR(10),
IDNO VARCHAR(15),
SNAME VARCHAR(75),
HOSCODE VARCHAR(3),
ROOM INT,
PRIMARY KEY(S_ID)
);

CREATE TABLE PRODUCT(
Product_ID VARCHAR(20),
Brand_Name VARCHAR (20),
KIND VARCHAR(20),
PRICE INT,
PRIMARY KEY (Product_ID)
);

CREATE TABLE Student_Spending